      ******************************************************************
      * Created: Fri, 16 Feb 2024 07:31:44 GMT
      * Generated by: IBM watsonx Code Assistant for Z Refactoring
      * Assistant
      * Workbook name: workbook3
      * Workbook id: a4f8c610-703a-427c-8cea-c9df083633de
      * Project: $demoapp_3c500e03-adfa-4fa5-9a65-8bf629692869
      ******************************************************************

       IDENTIFICATION DIVISION.
       PROGRAM-ID. COUSR01C.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
      ******************************************************************
       COPY COTTL01Y.
      * PATH : .../Cobol Include/COTTL01Y.CPY
      * THE FOLLOWING VARIABLES ARE USED FROM THE COPYBOOK :
      *01 CCDA-SCREEN-TITLE.
      *  05 CCDA-TITLE01    PIC X(40) VALUE
      *     '      AWS Mainframe Modernization       '.
      *  05 CCDA-TITLE02    PIC X(40) VALUE
      *     '  Credit Card Demo Application (CCDA)   '.
      *     '              CardDemo                  '.
      ******************************************************************
       COPY COUSR01.
      * PATH : .../Cobol Include/COUSR01.CPY
      * THE FOLLOWING VARIABLES ARE USED FROM THE COPYBOOK :
      *01  COUSR1AO REDEFINES COUSR1AI.
      *    02  TRNNAMEO  PIC X(4).
      *    02  PGMNAMEO  PIC X(8).
      *    02  TITLE01O  PIC X(40).
      *    02  TITLE02O  PIC X(40).
      *    02  CURDATEO  PIC X(8).
      *    02  CURTIMEO  PIC X(8).
      ******************************************************************
      * PATH : .../zOS Cobol/COUSR01C.cbl
       01 WS-VARIABLES.
         05 WS-PGMNAME                 PIC X(08) VALUE 'COUSR01C'.
         05 WS-TRANID                  PIC X(04) VALUE 'CU01'.
      ******************************************************************
       COPY CSDAT01Y.
      * PATH : .../Cobol Include/CSDAT01Y.CPY
      * THE FOLLOWING VARIABLES ARE USED FROM THE COPYBOOK :
      *01 WS-DATE-TIME.
      *  05 WS-CURDATE-MM-DD-YY.
      *    10  WS-CURDATE-MM             PIC 9(02).
      *    10  FILLER                    PIC X(01) VALUE '/'.
      *    10  WS-CURDATE-DD             PIC 9(02).
      *    10  FILLER                    PIC X(01) VALUE '/'.
      *    10  WS-CURDATE-YY             PIC 9(02).
      *  05 WS-CURDATE-DATA.
      *    10 WS-CURTIME-N REDEFINES WS-CURTIME PIC 9(08).
      *    10  WS-CURDATE.
      *      15  WS-CURDATE-YEAR         PIC 9(04).
      *      15  WS-CURDATE-MONTH        PIC 9(02).
      *      15  WS-CURDATE-DAY          PIC 9(02).
      *    10 WS-CURDATE-N REDEFINES WS-CURDATE PIC 9(08).
      *    10  WS-CURTIME.
      *      15  WS-CURTIME-MINUTE       PIC 9(02).
      *      15  WS-CURTIME-SECOND       PIC 9(02).
      *      15  WS-CURTIME-MILSEC       PIC 9(02).
      *      15  WS-CURTIME-HOURS        PIC 9(02).
      *  05 WS-CURTIME-HH-MM-SS.
      *    10  WS-CURTIME-HH             PIC 9(02).
      *    10  FILLER                    PIC X(01) VALUE ':'.
      *    10  WS-CURTIME-MM             PIC 9(02).
      *    10  FILLER                    PIC X(01) VALUE ':'.
      *    10  WS-CURTIME-SS             PIC 9(02).
      ******************************************************************

       LINKAGE SECTION.

       PROCEDURE DIVISION.
      ******************************************************************
      * PROGRAM NAME : Program:COBOL:COUSR01C
      * PROGRAM PATH : .../zOS Cobol/COUSR01C.cbl
      * STMT START LINE NUMBER : 214
      * STMT END LINE NUMBER : 233
       POPULATE-HEADER-INFO.

           MOVE FUNCTION CURRENT-DATE  TO WS-CURDATE-DATA

           MOVE CCDA-TITLE01           TO TITLE01O OF COUSR1AO
           MOVE CCDA-TITLE02           TO TITLE02O OF COUSR1AO
           MOVE WS-TRANID              TO TRNNAMEO OF COUSR1AO
           MOVE WS-PGMNAME             TO PGMNAMEO OF COUSR1AO

           MOVE WS-CURDATE-MONTH       TO WS-CURDATE-MM
           MOVE WS-CURDATE-DAY         TO WS-CURDATE-DD
           MOVE WS-CURDATE-YEAR(3:2)   TO WS-CURDATE-YY

           MOVE WS-CURDATE-MM-DD-YY    TO CURDATEO OF COUSR1AO

           MOVE WS-CURTIME-HOURS       TO WS-CURTIME-HH
           MOVE WS-CURTIME-MINUTE      TO WS-CURTIME-MM
           MOVE WS-CURTIME-SECOND      TO WS-CURTIME-SS

           MOVE WS-CURTIME-HH-MM-SS    TO CURTIMEO OF COUSR1AO.
      ******************************************************************
           EXIT PROGRAM.
